puns = {
    "create_event": [
        "Uninviting all guests",
        "Removing decorations",
        "Canceling catering",
        "Returning rented llama",
        "Deleting 'Sorry I can't make it' auto-response email",
        "Untagging yourself from Facebook event",
        "Erasing event from memory of all attendees",
        "Hiding evidence of party planning from significant other",
        "Canceling DJ, just playing Spotify on your phone instead",
        "Selling 'I survived the cancelled event' t-shirts on Etsy",
        "Deleting group chat for the event",
        "Returning borrowed party supplies",
        "Disposing of unused streamers and balloons",
        "Pretending it never happened",
        "Deleting reminder alarms from your phone",
        "Erasing all mentions of the event from social media",
        "Untelling your mom about the event",
        "Selling your ticket on eBay",
        "Changing your phone number",
        "Deleting the event from the calendar of the universe",
        "Deactivating the event page on eventbrite",
        "Letting down your pet who was going to be the 'mascot' of the event",
        "Returning the party hat you bought for yourself",
        "Changing the subject of the meeting invite",
        "Deleting the 'I'm so excited' texts you sent to your friends",
        "Canceling the 'after party' at your place",
        "Returning the 'congrats on the event' gift you received",
        "Removing the 'event day' count down from your phone's home screen",
        "Deleting the 'event theme' playlist from your Spotify account",
        "Removing the 'event' sticker from your car",
        "Canceling the clown you hired for the event",
        "Removing the 'event of the year' label from the invitation",
        "Deleting the 'event' hashtag from your Instagram bio",
        "Removing the 'event' filter from your snapchat",
        "Canceling the 'event' geofilter on Instagram",
        "Removing the 'event' location tag on Facebook",
        "Canceling the 'event' livestream on youtube",
        "Deleting the 'event' story on Instagram",
        "Removing the 'event' from your linkedin profile",
        "Deleting the 'event' from your website"
    ],
    "delete_event": [
        "Finding a pen that works",
        "Deciding on the perfect font for your event title",
        "Debating whether or not to invite your ex",
        "Checking to see if your co-worker is free before scheduling a meeting with them",
        "Realizing it's a national holiday and adjusting your plans accordingly",
        "Making sure there's enough snacks for the meeting",
        "Double checking the date to avoid scheduling conflicts with 'Game of Thrones' night",
        "Finding the perfect emoji to represent the event",
        "Reconsidering the whole thing and just going to the beach instead",
        "Finally adding the event and feeling a sense of accomplishment",
        "Realizing you forgot to invite your boss",
        "Adding a reminder to turn off your phone during the event",
        "Making sure the conference room is booked for the right date and time",
        "Deciding on whether to make the event recurring or not",
        "Adding the address and directions to the event details",
        "Sending out a reminder email to all attendees",
        "Realizing you scheduled the event for the wrong time zone",
        "Adding a note to bring your own coffee mug for the morning meeting",
        "Making sure the event is set to the correct privacy settings",
        "Sitting back and admiring your handy work",
        "Realizing you scheduled the event on a full moon night",
        "Double-checking the guest list to avoid any political correctness issues",
        "Deciding on whether to make the event a potluck or order in food",
        "Reminding yourself to bring the projector for the presentation",
        "Adding a poll for attendees to RSVP",
        "Sending a reminder to all attendees to wear their mask",
        "Checking the weather forecast to plan for indoor or outdoor event",
        "Adding a note to bring a lawn chair for the outdoor event",
        "Making sure the lighting of the room is adequate for the event",
        "Taking a deep breath and hitting the send button for the invitation",
        "Reminding yourself to call the speaker to confirm their attendance",
        "Adding a note to bring a yoga mat for the yoga class",
        "Checking the parking availability for the event",
        "Deciding on the perfect theme for the event",
        "Adding a note to bring a blanket for the movie night",
        "Sending a reminder to all attendees to bring a valid ID for the event",
        "Making sure the sound system is working for the event",
        "Adding a note to bring a camping chair for the concert",
        "Checking the availability of the first aid kit",
        "Feeling excited for the event and looking forward to it"
    ],
    "view_events": [
        "Checking if today is Monday or just another day of the week",
        "Searching for events that don't involve meetings",
        "Double checking if it's the correct year",
        "Making sure we're looking at the calendar and not a to-do list",
        "Searching for events that include free food",
        "Ensuring all events are correctly labeled as 'work' or 'fun'",
        "Checking for any suspiciously blank events",
        "Making sure there's at least one 'Netflix and Chill' event scheduled",
        "Cross-referencing with astrological chart for optimal scheduling",
        "Confirming that all events are in the future and not the past",
        "Searching for events with 'cake' in the title",
        "Checking for any events labeled as 'mandatory'",
        "Ensuring all events have a set location",
        "Making sure all events are properly color-coded",
        "Checking for any events that conflict with 'nap time'",
        "Searching for events that include 'happy hour'",
        "Checking for any events labeled as 'top secret'",
        "Ensuring all events have a set time",
        "Making sure all events are properly labeled as 'public' or 'private'",
        "Checking for any events that conflict with 'gaming night'",
        "Searching for events that include 'pizza'",
        "Checking for any events labeled as 'team building'",
        "Ensuring all events have a set duration",
        "Making sure all events are properly labeled as 'urgent' or 'non-urgent'",
        "Checking for any events that conflict with 'book club'",
        "Searching for events that include 'chocolate'",
        "Checking for any events labeled as 'performance review'",
        "Ensuring all events have a set reminder",
        "Making sure all events are properly labeled as 'in-person' or 'virtual'",
        "Checking for any events that conflict with 'yoga class'",
        "Searching for events that include 'coffee'",
        "Checking for any events labeled as 'brainstorming session'",
        "Ensuring all events have a set invitees",
        "Making sure all events are properly labeled as 'recurring' or 'one-time'",
        "Checking for any events that conflict with 'dinner with friends'",
        "Searching for events that include 'ice cream'",
        "Checking for any events labeled as 'annual company retreat'"
    ],
    "reschedule_event": [
        "Finding the perfect excuse for why you can't make it",
        "Searching for a time that works for everyone",
        "Realizing you accidentally scheduled it for a holiday",
        "Panicking because you can't find the invite",
        "Trying to remember who even invited you in the first place",
        "Deciding whether or not to just ghost the whole thing",
        "Checking to see if your favorite TV show is on at the new time",
        "Making sure your significant other is also free",
        "Trying to find a time that doesn't conflict with your nap schedule",
        "Convincing yourself it's not too late to cancel",
        "Realizing you're double booked with another event",
        "Checking the weather forecast for the new date",
        "Making sure the new time doesn't conflict with happy hour",
        "Seeing if the new time works better for your astrological chart",
        "Ensuring the new time won't interfere with your daily video game sessions",
        "Considering whether or not you even want to go anymore",
        "Checking to see if the new date is on a full moon",
        "Making sure the new time doesn't conflict with your favorite podcast",
        "Seeing if the new date works with your workout schedule",
        "Checking to see if the new time is during a good sale at your favorite store",
        "Ensuring the new date doesn't interfere with your book club meeting",
        "Checking to see if the new time is during a good Netflix binge",
        "Making sure the new date doesn't conflict with your cat's grooming appointment",
        "Checking to see if the new time is during a good nap time",
        "Ensuring the new date doesn't interfere with your online gaming guild's raid night",
        "Making sure the new time doesn't conflict with your favorite cooking show",
        "Checking to see if the new date is on a good hair day",
        "Ensuring the new time doesn't interfere with your daily yoga practice",
        "Making sure the new date doesn't conflict with your favorite sports team's game",
        "Checking to see if the new time is during a good happy hour",
        "Ensuring the new date doesn't interfere with your daily meditation session",
        "Checking to see if the new time is during a good time to catch up on the news",
        "Making sure the new date doesn't conflict with your favorite band's concert",
        "Ensuring the new time doesn't interfere with your daily walk",
        "Checking to see if the new date is on a good day to do laundry",
        "Making sure the new time doesn't conflict with your favorite podcast",
        "Ensuring the new date doesn't interfere with your daily video game sessions",
    ]
}
